# Site settings
title: PagSeguro Transparente para Magento
email: pagseguro-transparente@ricardomartins.net.br
description: > # this means to ignore newlines until "baseurl:"
  Módulo PagSeguro transparente para Magento, open source, criado por Ricardo Martins.
#local:
#baseurl: "/" # the subpath of your site, e.g. /blog/
#prod:
baseurl: "/PagSeguro-Magento-Transparente"
url: "http://r-martins.github.io/PagSeguro-Magento-Transparente/" # the base hostname & protocol for your site
twitter_username: r_martins
github_username:  r-martins

# Build settings
markdown: kramdown
